accelerator: null
accumulate_grad_batches: null
amp_backend: native
amp_level: null
aug_prob: 0.5
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 32
benchmark: null
block_num: 8
check_val_every_n_epoch: 1
data_dir: ../dataset
dataset: img_data
default_root_dir: null
detect_anomaly: false
deterministic: null
devices: null
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
fast_dev_run: false
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: null
hid: 64
in_channel: 3
ipus: null
layer_num: 5
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
load_best: false
load_dir: null
load_v_num: null
load_ver: null
log_dir: lightning_logs
log_every_n_steps: 50
logger: true
loss: bce
lr: 0.001
lr_decay_min_lr: 1.0e-05
lr_decay_rate: 0.5
lr_decay_steps: 20
lr_scheduler: null
max_epochs: 100
max_steps: -1
max_time: null
mean_sen:
- 0.485
- 0.456
- 0.406
min_epochs: null
min_steps: null
model_name: baseline_net
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
no_augment: false
num_nodes: 1
num_processes: null
num_sanity_val_steps: 2
num_workers: 8
overfit_batches: 0.0
plugins: null
precision: 32
profiler: null
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
seed: 1234
std_sen:
- 0.229
- 0.224
- 0.225
strategy: null
sync_batchnorm: false
tpu_cores: null
track_grad_norm: -1
val_check_interval: null
weight_decay: 1.0e-05
weights_save_path: null
